### ISSUE TITLE
The raw_id_fields doesn't work

### ISSUE THREAD

**Issue by c4x** [douglasmiranda/django-admin-bootstrap#101]
like this, when do not use the raw_id_fields 
![image](https://cloud.githubusercontent.com/assets/1243445/21562679/b6466f4a-ceb5-11e6-9963-045199146761.png)
the page show this:
![image](https://cloud.githubusercontent.com/assets/1243445/21562694/dbc78056-ceb5-11e6-900b-f98e2060dc2e.png)
but when use the raw_id_fields:
![image](https://cloud.githubusercontent.com/assets/1243445/21562720/19445396-ceb6-11e6-81d2-fcf42bd1adca.png)
the page show nothing, just a text:
![image](https://cloud.githubusercontent.com/assets/1243445/21562733/2c343e80-ceb6-11e6-916b-cfe3cbd457b4.png)
so, what wrong in this?

**Comment by c4x** [comment]
And the html is:
![image](https://cloud.githubusercontent.com/assets/1243445/21562771/753922e4-ceb6-11e6-827d-9f83a63e9ed4.png)
when change the backgroud-color, I get this:
![image](https://cloud.githubusercontent.com/assets/1243445/21562830/e4817c82-ceb6-11e6-8225-921eae69666f.png)

**Comment by douglasmiranda** [comment]
What Django version are you using?

**Comment by c4x** [comment]
Django 1.10.4 and Python 3.5.0

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/commit/93fd805063922c3a5db28a874dfd2e2e2408dee8
