### ISSUE TITLE
django 1.11 compatibility

### ISSUE THREAD

**Issue by eskhool** [douglasmiranda/django-admin-bootstrap#105]
Starting an issue to get a discussion on Django 1.11 compatibility going

**Comment by eskhool** [comment]
@douglasmiranda, as the BD(FL?) for the project, could you chime in quickly as to the plan of making the release compatible with 1.11. Since this release migrate to using template fragments, it will likely be more work and we should align efforts.

**Comment by eskhool** [comment]
@douglasmiranda, any updates on the plans (or lack of) for Django 1.11? Any update would give us a plan on how to proceed with the same as we don't want to duplicate effort nor step on any toes?

**Comment by douglasmiranda** [comment]
Hey @eskhool, do you think you can help me to make it compatible with Django 1.11?

**Comment by eskhool** [comment]
Sure @douglasmiranda but we have our own list of other enhancements (which bring along design decisions) which will get interspersed with your base. Right now we maintain them as a list of patches on top of the current code and reapply them on top of the latest master/released code from your repo.

Also is the javascript code written in coffeescript? Is that checked into the repo?

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/commit/93fd805063922c3a5db28a874dfd2e2e2408dee8

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/commit/3016ca9ed5392f05a925a2db06a391e1f525f461

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/commit/058111e5889dca58cac3e9919a86f2230ca45a24

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/commit/ec63dcf601154f23dd873301d0a5a26ff077a340

**Comment by douglasmiranda** [comment]
Okay, master branch is now compatible with Django 1.11, will release a new version.
