### ISSUE TITLE
Compatibility with Django CMS and djangocms-text-ckeditor

### ISSUE THREAD

**Issue by GregoryAveryWeir** [douglasmiranda/django-admin-bootstrap#106]
(also submitted as divio/djangocms-text-ckeditor#431)

django-admin-bootstrap generally works great with Django CMS, but we're running into an issue with a certain plugin. With django-admin-bootstrap installed, the djangocms-text-ckeditor app seems to fail to register itself.

When loading a change form while editing a CMS page, we get the following error:

**NoReverseMatch at /admin/cms/page/edit-plugin/1/**
`Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': 'djangocms_text_ckeditor'}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>django_comments|auth|updates|filer|cms|tagging|zinnia|sites|djangocms_snippet)/$']`

As you can see, djangocms-text-ckeditor isn't listed in the app_list, but I expect it to be. Is django-admin-bootstrap doing something that would interfre with the registration of another app in the admin?

**Comment by douglasmiranda** [comment]
The template tag `render_menu_app_list` use `'app_list'`.

So it's probably messing up, only why I don't know.

Need to find a better way to render the lateral menu.

**Comment by douglasmiranda** [comment]
1eeade05f44b7d2bb59975103114c049406df0c4

**Comment by GregoryAveryWeir** [comment]
This still appears to be a problem with:

Django==1.11.13
django-cms==3.6.0
djangocms-text-ckeditor==3.5.3
bootstrap-admin==0.4.2
