### ISSUE TITLE
layout is incorrect like this 

### ISSUE THREAD

**Issue by mysteryHJJ** [douglasmiranda/django-admin-bootstrap#108]
![image](https://user-images.githubusercontent.com/18051097/28163230-db4f9916-67fc-11e7-9a9c-378dc4e0a2ff.png)

**Comment by douglasmiranda** [comment]
That must be cache, have you tried to clean the browser cache?

**Comment by tanmaybaranwal** [comment]
For me, it's coming something like this?
![screen shot 2017-08-29 at 12 57 29 pm](https://user-images.githubusercontent.com/7475655/29809431-c53b6af6-8cb9-11e7-9e1b-6b721df87cfa.png)

**Comment by douglasmiranda** [comment]
I'm unable to reproduce.

Post a demo, and describe how to reproduce, please.

**Comment by tanmaybaranwal** [comment]
Actually we have moved to some other package. I will have to reinstall the package.

**Comment by douglasmiranda** [comment]
Ok, if you guys @mysteryHJJ  @tanmaybaranwal face this error again let me know the details.
