### ISSUE TITLE
Change default admin logo

### ISSUE THREAD

**Issue by farhatnawaz** [douglasmiranda/django-admin-bootstrap#110]
I have installed this and it is working just fine. But the thing is that I want to change the default logo. How can I do that? I have tried overriding the base.html and base_site.html files but to no avail. My base.html code is:

```
{% extends "admin:admin/base.html" %}
{% load theming_tags %}
{% load staticfiles %}
{% block blockbots %}
    {{ block.super }}
    {# Using blockbots ensures theming css comes after any form media and other css #}
    {% render_theming_css %}
    <style type="text/css">
    #header #branding h1 {
        background-image: url("bootstrap_admin/img/logo-140x60.png");
    }
    </style>
{% endblock %}

{% block branding %}
<a href="{% url 'admin:index' %}" class="django-admin-logo">
    <!-- Django Administration -->
    <img src="{% static "bootstrap_admin/img/logo-140x60.png" %}" alt="{{ site_header|default:_('Django Admin') }}">
</a>
{% endblock branding %}
```

And my base_site.html code is:

```
{% extends "admin/base.html" %}
{% load staticfiles %}  }

{% block title %}{{ title }} | {{ site_title|default:_('site admin') }}{% endblock %}

{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Administration') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}
```

So how can I change the logo?

**Comment by douglasmiranda** [comment]
How are your settings?

If you want to change the logo globally you could create the dir 'templates/' in the same level as 'manage.py' (or even whatever you like) and set on `TEMPLATES` your global templates directory:

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        # ......
    }
]
```

So you will put your custom base.html in templates/admin/base.html

What  Django version are you using?

**Comment by jaswanthm** [comment]
Hey @douglasmiranda, I am trying to add a template as well. I followed your instructions. 

I was able to override the `base_site.html` file but no luck with `base.html` or `login.html`. 

Very strange. Would be great if you can help with this. Thanks

**Comment by farhatnawaz** [comment]
@douglasmiranda thank you for your reply but it's a pretty old thread and I was able to resolve the issue long ago and forgot to close the issue.
