### ISSUE TITLE
Collapse class does not work properly with StackedInline

### ISSUE THREAD

**Issue by ko1es** [douglasmiranda/django-admin-bootstrap#116]
So the topic describes everything we need.

`
class FooAdminInline(StackedInline):
    classes = ['collapse']
`
does not works properly - "show" button does not displayed, but form and everything hidden. Reason is different ways of `edit_inline/stacked.html` template in original Django admin templates and bootsrap_admin.
Original - https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/edit_inline/stacked.html
Bootstrap - https://github.com/douglasmiranda/django-admin-bootstrap/blob/master/bootstrap_admin/templates/admin/edit_inline/stacked.html

**Comment by ko1es** [comment]
P.S. in version 0.3.8 'collapse' became available for TabularInline by addind `inline_admin_formset.classes` object into `edit_inline/tabular.html`, unfortunately `stacked.html` was ignored.
Tabular classes fix commit - https://github.com/douglasmiranda/django-admin-bootstrap/commit/df06492a1c8edc7c1ba1348a2a4db81657763356#diff-a8bce4d1bd9cd2be399c0d73a59d8938R5

**Comment by douglasmiranda** [comment]
You're right, fixing right now.

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/releases/tag/0.3.9

**Comment by ko1es** [comment]
wonderful, ty
