### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by ronaldFeri** [douglasmiranda/django-admin-bootstrap#117]
Hi, 
I'm quiet new to Django programing and I just developed some small applications. I have a python application and want to let users do some configurations via a Django web application, such as selecting a path to read/write files or time intervals to read data. Users need to be authenticated first. Can I deploy your project and how can I do it? thanks in advanced. 
Ronald

**Comment by douglasmiranda** [comment]
Hello @ronaldFeri, my project it's just a theme for [Django admin](https://docs.djangoproject.com/en/2.0/ref/contrib/admin/).

If you're new to Django, get familiar with Django Admin, installing third-party apps to your Django project, then come back here, and just follow the steps on [INSTALL](https://github.com/douglasmiranda/django-admin-bootstrap#install) section on the project's README.
