### ISSUE TITLE
raw_id_fields not working 

### ISSUE THREAD

**Issue by ArijitWeird** [douglasmiranda/django-admin-bootstrap#118]
I have been using django-admin-bootstrap for sometimes for my project. Everything working smoothly till I noticed no search bar beside raw_id_fields in django admin.
bootstrap-admin==0.3.8
django version==1.10.2

Any suggestion??

**Comment by douglasmiranda** [comment]
I've tested on Django 2.0 and 1.11 and it worked.

<img width="902" alt="screen shot 2018-01-28 at 21 20 08" src="https://user-images.githubusercontent.com/542013/35489216-9a14785a-0472-11e8-9a17-c19b9def1cdb.png">

I didn't test on 1.10, but it should work.

I have to put on our README, I'm supporting only 1.11 and above.

To cover other versions I would need more contributors dedicated to supporting some other versions.
