### ISSUE TITLE
select all is not working in change_list

### ISSUE THREAD

**Issue by myereach** [douglasmiranda/django-admin-bootstrap#122]
Dear Sir,
This is a awesome project and I like it. After play around, I suddenly found in the list view, the select all checkbox is not working? is it a bug or just happened on me?
my version is bootstrap-admin (0.3.9)

Thanks for any help

**Comment by douglasmiranda** [comment]
What version of Django are you using?

**Comment by myereach** [comment]
Thanks for your response. my django version is 1.9.1
the following is the pip list output:
bootstrap-admin (0.3.9)
Django (1.9.1)
pip (9.0.1)
setuptools (28.8.0)

**Comment by myereach** [comment]
does anyone have the same issue?
The following is the screen shot. When i checked the select all box, the rest of select box were not checked. 
![image](https://user-images.githubusercontent.com/9948830/36720259-76877aae-1be2-11e8-8f06-18193e3e0016.png)

**Comment by myereach** [comment]
@douglasmiranda the issue seems to be the version of Djang. I upgraded to 1.11.10 and the problem solved.

**Comment by douglasmiranda** [comment]
Thanks @myereach xD
