### ISSUE TITLE
Configure Admin Headers and side menu

### ISSUE THREAD

**Issue by gerhardlouis** [douglasmiranda/django-admin-bootstrap#123]
How would one go about modifying the Headers and so forth

**Comment by PEDROMHB** [comment]
buscas personalizar the admin headers and side menu?

**Comment by douglasmiranda** [comment]
Same way you override Django Admin templates: https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#admin-overriding-templates

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap#customize
