### ISSUE TITLE
Add button "Go to site"

### ISSUE THREAD

**Issue by PEDROMHB** [douglasmiranda/django-admin-bootstrap#124]
Hi! Recently use this application to customize my django admin, note that it lacked a button that would take me directly to the main site (index.html) I took the attribution of creating and adding said button to the template base.html and it works very well, I attach capture and I hope to be able to contribute this small detail to this project soon. 
![screenshot](https://user-images.githubusercontent.com/37071125/36992199-1eb1f8b2-20a2-11e8-9f04-8c29fd1c58a2.png)

**Comment by douglasmiranda** [comment]
Nice, there are instructions for contributing on README: https://github.com/douglasmiranda/django-admin-bootstrap#contributing

Send a PR and I'll review.

**Comment by PEDROMHB** [comment]
Hi! good I will follow the instructions to contribute friend!

**Comment by PEDROMHB** [comment]
friend I am new using github and I do not know how to create a new branch, here I leave the template that you modify(line 113)
[go to the site.zip](https://github.com/douglasmiranda/django-admin-bootstrap/files/1803056/go.to.the.site.zip)
 and the file urls.py of the project, so that the go to the site button works correctly it is necessary to configure a url with the name of ' home ' in said file,
 I hope to continue contributing with this great project.
