### ISSUE TITLE
Search tooltip won't fade

### ISSUE THREAD

**Issue by diogosimao** [douglasmiranda/django-admin-bootstrap#126]
Hi!
Sorry if I miss some info opening the issue. I may go back and edit it.
This is the example I want to give:
![peek 2018-06-13 09-32](https://user-images.githubusercontent.com/8460840/41351574-2c9d8bd2-6eed-11e8-996d-5b635dcf0a39.gif)
and basically it is just the _search tooltip_ that won't fade and stays fixed after clicking.

**Comment by douglasmiranda** [comment]
Thanks for reporting, I will look into it.

And feel free to create a pull request if you fix this before I do. xD

**Comment by douglasmiranda** [comment]
I could not replicate this here if you still have let me know.
