### ISSUE TITLE
how to do the responsive dashboard?

### ISSUE THREAD

**Issue by JohnHour89** [douglasmiranda/django-admin-bootstrap#130]
Hi, Sir, may I know how to change the dashboard to become responsive like this? Thank you.

![screen shot 2018-10-10 at 10 01 41 am](https://user-images.githubusercontent.com/19371443/46709160-f8f6da00-cc74-11e8-96db-396e3eca88c9.png)

When reduce the size of the browser, the dashboard was running from the alignment. I want it to become like this, thank you:

![screen shot 2018-10-10 at 10 02 03 am](https://user-images.githubusercontent.com/19371443/46709179-11ff8b00-cc75-11e8-9050-42fe9b201c64.png)

**Comment by douglasmiranda** [comment]
Hey @JohnHour89, I see you've customized the dashboard's CSS. That code is online/public so we can see what you did that broke when resizing the window?
