### ISSUE TITLE
Existing link values overflow main form div

### ISSUE THREAD

**Issue by dlareau** [douglasmiranda/django-admin-bootstrap#141]
<img width="970" alt="Screen Shot 2019-03-13 at 10 50 55 AM" src="https://user-images.githubusercontent.com/2934378/54288834-828d3980-457e-11e9-8a88-fa11d423ea8d.png">

It would seem that on a URL field widget, the existing value for the URL doesn't wrap properly. It would seem adding the following CSS: (taken from [here](https://stackoverflow.com/questions/5241369/word-wrap-a-link-so-it-doesnt-overflow-its-parent-div-width))
```css
    white-space: pre-wrap; /* css-3 */    
    white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
    white-space: -pre-wrap; /* Opera 4-6 */    
    white-space: -o-pre-wrap; /* Opera 7 */    
    word-wrap: break-word; /* Internet Explorer 5.5+ */
```
To the `<a>` tag here:
https://github.com/douglasmiranda/django-admin-bootstrap/blob/17c2de578fd0d0517d154191da73ddc79eca81d1/bootstrap_admin/templates/admin/widgets/url.html#L5

Fixes the issue. 

I made an issue rather than a pull request because I don't know the most logical place/selectors for the new CSS. 

Hopefully this helps.

**Comment by douglasmiranda** [comment]
Thanks! xD
