### ISSUE TITLE
Template issue

### ISSUE THREAD

**Issue by mj-hardy** [douglasmiranda/django-admin-bootstrap#146]
I have tired installing this great package but am having an issue with the layout. I have tied both in my application and in clean Django project.

I'm using Django 2.2 and python 3.6

Kind Regards

Matt 

![Template issues](https://user-images.githubusercontent.com/46336199/60473699-a43b3980-9cb1-11e9-8f8a-adbcf2738cfe.PNG)

**Comment by douglasmiranda** [comment]
Clear your browser cache. That's probably the issue. =)

**Comment by mj-hardy** [comment]
Thanks, that was it
