### ISSUE TITLE
Unable to import bootstrap_admin on django 3.0.3

### ISSUE THREAD

**Issue by samarthkathal** [douglasmiranda/django-admin-bootstrap#150]
I tried installing this package on a clean built of a working app running on django 3.0.3 (python version 3.8.1)

It is throwing a ` ModuleNotFoundError: No module named 'bootstrap_admindjango' ` error.
this looks more like a typo.
I am not much familiar with the project can anyone please look into this or atleast point me in the right direction?

Thanks.

![2020-02-19-010452_1920x1080_scrot](https://user-images.githubusercontent.com/34944862/74771371-09c94e00-52b4-11ea-9ff2-859a319d184b.png)

**Comment by douglasmiranda** [comment]
You're missing a comma after `"bootstrap_admin"`.

You wrote:

```python
[
    'bootstrap_admin'
    'django.contrib.admin'
    ...
```

It should be:

```python
[
    'bootstrap_admin',
    'django.contrib.admin'
    ...
```

**Comment by samarthkathal** [comment]
Yes, sorry about that. I got it working and forgot to close this.
Thanks :)
