### ISSUE TITLE
Six removed from django 3.0

### ISSUE THREAD

**Issue by ortegoncarlos** [douglasmiranda/django-admin-bootstrap#151]
Hello thanks for your work, the library django.utils.six was removed from django 3.0 

[https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis)

```
  File "django_projects/Asostartups/venv/lib/python3.7/site-packages/bootstrap_admin/templatetags/bootstrap_admin_template_tags.py", line 5, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/Users/carlosortegon/django_projects/Asostartups/venv/lib/python3.7/site-packages/django/utils/__init__.py)

During handling of the above exception, another exception occurr
```

**Comment by ortegoncarlos** [comment]
actually you just imported but don't use it, it can be erase that line 

from django.utils import six

**Comment by Nefonfo** [comment]
I have the same problem with the import name 'six'

**Comment by ortegoncarlos** [comment]
not the "best practice" way to fix it but a hacky way:

Go to 
/site-packages/bootstrap_admin/templatetags/bootstrap_admin_template_tags.py 
and erase line
```
from django.utils import six
```

**Comment by gassc** [comment]
Looks like it was addressed with 8646af137a53520344d31a7c3d6e4878a812b1bf, but not incorporated in the [the recent 0.4.3 release](https://github.com/douglasmiranda/django-admin-bootstrap/releases/tag/0.4.3).

**Comment by nodarai** [comment]
@ortegoncarlos maybe worth to make a new release in order to make the package compatible with Django 3

**Comment by eghlima** [comment]
@ortegoncarlos
Thanks for this library. as most of users using the django3, I think that is better to have a new release.
when you think we can have a new release?

**Comment by douglasmiranda** [comment]
I'll be pushing a new release very soon, sorry for the delay.

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/releases/tag/0.4.4
