### ISSUE TITLE
No module named apps

### ISSUE THREAD

**Issue by nordbit** [douglasmiranda/django-admin-bootstrap#50]
```
from django.apps import apps

'bootstrap_admin_template_tags' is not a valid tag library: ImportError raised loading bootstrap_admin.templatetags.bootstrap_admin_template_tags: No module named apps
```

branch django1.7_bootstrap_3

**Comment by grillazz** [comment]
Sorry but I have this err in Django 1.6.10. I can't migrate to 1.7 yet. Any sugestions ?

**Comment by douglasmiranda** [comment]
Well, this is complicated. I'll look into it, to see if I have any suggestions.

**Comment by grillazz** [comment]
Thx for checking

**Comment by grillazz** [comment]
ok solved i updated other libarary and now Im able to use Django 1.7 :)
