### ISSUE TITLE
Multiple choices for filters

### ISSUE THREAD

**Issue by Seether85** [douglasmiranda/django-admin-bootstrap#60]
Hello, I'm trying to filter table results with more than a parameter for the same category of filter.
For example, in a table of cities:
"All cities in Virginia AND in Nevada".
Right now I can't seem to be able to do that, as I can only pick either a single state, or all of them.
Would it be possible to do it somehow?
Thanks

**Comment by gamesbook** [comment]
This is not really a bootstrap issue ... you will need to create your own filter; see, for example, SimpleListFilter described here:
https://docs.djangoproject.com/en/1.7/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter

**Comment by Seether85** [comment]
Mmh, I remember I could pick an arbitrary number of choices in this same scenario before using admin-bootstrap, and without defining any custom filter at all.
Anyway, if it's just a matter of that, perhaps it won't be too much a pain to handle.

**Comment by douglasmiranda** [comment]
Closing for now, if something goes wrong with filters and django-admin-bootstrap feel free to reopen.
