### ISSUE TITLE
Collapsible field sets are not shown

### ISSUE THREAD

**Issue by ahalma** [douglasmiranda/django-admin-bootstrap#61]
A field set with class "collapse" doesn't show up in the rendered form. 
Example from the [django tutorial](https://docs.djangoproject.com/en/1.7/intro/tutorial02/):

```python
class QuestionAdmin(admin.ModelAdmin):
    fieldsets = [
        (None,               {'fields': ['question_text']}),
        ('Date information', {'fields': ['pub_date'], 'classes': ['collapse']}),
    ]
```

Here the 'date information' will not show...

**Comment by douglasmiranda** [comment]
Fixed! :D
