### ISSUE TITLE
What is the proper way to provide a custom logo?

### ISSUE THREAD

**Issue by ahalma** [douglasmiranda/django-admin-bootstrap#62]
The side bar menu now shows a logo saying: "Django admin", using the image found in the bootstrap_admin template: bootstrap_admin/static/img/logo-140x60.png. 

What is the best way to change this to my own custom logo in my app?

**Comment by pbojinov** [comment]
I was able to add my own logo by overextending the admin app's `base.html` with my own and overriding the branding block. My `base.html` file looks like this:

```
{% overextends "admin/base.html" %}
{% load staticfiles %} 

{% block branding %}
<a href="{% url 'admin:index' %}" class="django-admin-logo">
  	<!-- Django Administration -->
  	<img src="{% static "images/branding/logo.png" %}" alt="{{ site_header|default:_('Django Admin') }}">
</a>
{% endblock branding %}
```

**Comment by zchking** [comment]
which path do you put the base.html ?I've try put it to root /templates/base.html,but it seem not work.thanks very much.

**Comment by douglasmiranda** [comment]
When overriding templates or static files from admin you will have to put the templates in templates/admin/YOURTEMPLATE.html

https://docs.djangoproject.com/en/1.7/ref/contrib/admin/#admin-overriding-templates

If you just want to override the logo without custom html/css, just override the logo file in 

/static/bootstrap_admin/img/logo-140x60.png

**Comment by witalobenicio** [comment]
Hi...i'm not able to change the logo of admin. 
I did a collectstatic and change the default logo to my own logo, but when i access the admin the default logo is still there.
What i made wrong?

**Comment by farhatnawaz** [comment]
@douglasmiranda I ran `python manage.py collectstatic` in the admin directory and replaced the logo file but it still shows the default logo. I think the app is not pointing to the local static files. What should I do?
