### ISSUE TITLE
How to override recent_actions block?

### ISSUE THREAD

**Issue by alrusdi** [douglasmiranda/django-admin-bootstrap#68]
I've added a file into my application templates folder 

admin/index.html

with contents:

{% extends "bootstrap_admin:admin/index.html" %}
{% block recent_actions %}
{% endblock %}

And i was expected to have empty recent_articles block but it didnt happend.
So how to override recent_actions block?

**Comment by pbojinov** [comment]
It looks like some of the recent_actions stuff is also leaked in the content block above it. Have you tried adding an empty content block instead of recent_actions?
```python
{% block content %}
{% endblock content %}
```

**Comment by alrusdi** [comment]
It's my fault. Impossible to override this block this way.
