### ISSUE TITLE
ajax search 

### ISSUE THREAD

**Issue by Summer88** [douglasmiranda/django-admin-bootstrap#71]
Thanks for sharing this beautiful and useful app!

I've noticed that on the first page of the admin it is available an ajax search field, when you type in it  the following rows are filtered directly. 
It is possible to use this feature also in the single adminmodel pages? how can it be enabled?

**Comment by douglasmiranda** [comment]
Hello @Summer88 =]

I'ts not a ajax search, i'ts just a search in existing html table.

I did with http://www.listjs.com/
