### ISSUE TITLE
Compare with grappelli, which one is the best?  

### ISSUE THREAD

**Issue by dutwfk** [douglasmiranda/django-admin-bootstrap#72]

**Comment by douglasmiranda** [comment]
This is not look like a valid issue, but the one fits your needs is the best. Grappelli is awesome.

So you should try each one and provide us feedback. If you like django-admin-bootstrap we are here for you, if you like Grappelli I bet Patrick Kranzlmueller will be there for you. =]

**Comment by thebenwaters** [comment]
@dutwfk  I found grappelli too heavy so I switched to DAB

**Comment by dutwfk** [comment]
Thank you very much! :100: @douglasmiranda

**Comment by douglasmiranda** [comment]
:)
