### ISSUE TITLE
In-fieldsets inputs are not assigned "error" class

### ISSUE THREAD

**Issue by Seether85** [douglasmiranda/django-admin-bootstrap#78]
As per subject.
Non-validating fields after ModelForm's clean() method don't get the red border, as the parent containing divs (.form-row) aren't assigned the "has-error" class.

**Comment by douglasmiranda** [comment]
Could you provide the steps to reproduce?

Here I'm getting the red border.

<img width="662" alt="screen shot 2017-11-28 at 00 35 32" src="https://user-images.githubusercontent.com/542013/33301373-3700f5be-d3d4-11e7-9835-054e8c8330f1.png">

**Comment by Seether85** [comment]
I am sorry @douglasmiranda but I have given up Django quite few years ago, so unfortunately I have no longer idea what we are talking about :)
