### ISSUE TITLE
github group for central collection of extensions

### ISSUE THREAD

**Issue by michaelkuty** [douglasmiranda/django-admin-bootstrap#82]
is possible create new github group as central repository for all related extensions ?

i want create FeinCMS fixes to new extension but under my namespace is hidden for other peoples

**Comment by michaelkuty** [comment]
https://github.com/django-admin-bootstrap
here is, please can you accept invite ?

**Comment by douglasmiranda** [comment]
I've removed the django-admin-bootstrap/django-admin-bootstrap so I can transfer douglasmiranda/django-admin-bootstrap.

**Comment by michaelkuty** [comment]
yes and and close this issue
